name: Docker build and Pytest

on:
  workflow_dispatch 
jobs:
  build:
   runs-on: ubuntu-latest
  
   steps:
     - uses: actions/checkout@v2
     - name: Build Docker image 
       run: docker build -t balltracking .
     - name: Run tests inside the container
       run: docker run balltracking pytest
