name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: start Docker
      run: |
        docker build -t balltracking .
    - name: Analysing the code with pylint inside docker
      run: docker run -v $(pwd):/balltracking --ipc host balltracking pylint $(git ls-files '*.py')
